baseURL = 'https://localhost:1313/'
languageCode = 'en-us'
title = 'ivy (local dev)'
buildDrafts = true # only on local, to preview

copyright = ''
paginate = 10
defaultContentLanguage = 'en'

cleanDestinationDir = true
hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ['error-remote-getjson']

[module]
[module.hugoVersion]
extended = true
min = '0.119.0'

# Ordering here matters, higher imports in this file have authority
[[module.imports]]
  path = 'github.com/hugomods/images'
[[module.imports]]
  path = 'github.com/hugomods/katex'
[[module.imports]]
  path = 'github.com/hugomods/mermaid'
[[module.imports]]
  path = 'github.com/roninro/hugo-theme-puppet'

[outputs]
home = ['HTML', 'JSON', 'RSS']

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = 'categories'
tag = 'tags'
series = 'series'

[markup]
[markup.highlight]
lineNos = false
style = 'dracula'
tabWidth = 2

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = 'poli-statement'
name = 'political statement'
url = '/poli-statement/'
weight = -100
[[menu.main]]
identifier = 'projects'
name = 'projects'
url = '/projects/'
weight = 0
[[menu.main]]
identifier = 'resume'
name = 'resume'
url = '/resume/'
weight = 10
[[menu.main]]
identifier = 'hardware'
name = 'hardware'
url = '/rolecall/'
weight = 20

[params]
description = 'Documenting my Homelab, 3D printing, and Software Development projects.'
keywords = 'blog,developer,personal'
img_home = '/img/header-miata.webp'

[params.sidebar]
enable = true
bio = 'Long time tech enthusiast, recent UCSD Cognitive Science graduate.'

[params.social]
github = 'ivylikethevine'
linkedin = 'ivylikethevine'
medium = '@ivylikethevine'

[params.mermaid]
js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'
