baseURL = 'https://ivylikethevine.pages.dev/'
languageCode = 'en-us'
title = 'ivy (development)'

cleanDestinationDir = true

copyright = ''
paginate = 10
defaultContentLanguage = 'en'

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ['error-remote-getjson']

[module]
[module.hugoVersion]
extended = true
min = '0.110.0'

# Ordering here matters, higher imports in this file have authority
[[module.imports]]
  path = 'github.com/hugomods/images'
[[module.imports]]
  path = 'github.com/hugomods/katex'
[[module.imports]]
  path = "github.com/hugomods/mermaid"
[[module.imports]]
  path = 'github.com/roninro/hugo-theme-puppet'

[outputs]
home = ['HTML', 'JSON', 'RSS']

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = 'categories'
tag = 'tags'
series = 'series'

[markup]
[markup.highlight]
lineNos = false
style = 'dracula'
tabWidth = 2

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = 'projects'
name = 'projects'
url = '/'
weight = -100
[[menu.main]]
identifier = 'resume'
name = 'resume'
url = '/resume/'
weight = 10

[params]
description = "My personal projects & writings"
keywords = "blog,developer,personal"
img_home = "/img/front-horizontal2.jpg"
# img_404 = "img/404-bg.jpg"

[params.social]
github = 'ivylikethevine'
linkedin = 'ivylikethevine'
medium = '@ivylikethevine'

[params.mermaid]
  js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'
