baseURL = 'https://ivylikethevine.com/'
languageCode = 'en-us'
title = 'ivy (likethevine)'
theme = 'puppet'

copyright = ''
paginate = 3
defaultContentLanguage = 'en'

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ['error-remote-getjson']


[outputs]
home = ['HTML', 'JSON', 'RSS']

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = 'categories'
tag = 'tags'
series = 'series'

[markup]
[markup.highlight]
lineNos = false
style = 'dracula'
tabWidth = 2

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = 'home'
name = 'home'
url = '/'
weight = -100
[[menu.main]]
identifier = 'resume'
name = 'resume'
url = '/resume/'
weight = 10
[[menu.main]]
identifier = 'homelab'
name = 'homelab'
url = '/homelab/'
weight = 20
# [[menu.main]]
# identifier = 'projects'
# name = 'projects'
# url = '/projects/'
# weight = 30

[params]
description = "My personal projects & writings"
keywords = "blog,developer,personal"
img_home = "/front-horizontal2.jpg"
img_404 = "img/404-bg.jpg"


[params.social]
github = 'ivylikethevine'
linkedin = 'ivylikethevine'
medium = '@ivylikethevine'

[params.mermaid]
theme = "dark"
align = "center"
